name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "52 16 * * *"  # 22:45 IST
  workflow_dispatch:

# This is the critical fix:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile 3D Contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Upload Generated Content
        run: |
          git config --global user.name '${{ github.repository_owner }}'
          git config --global user.email '${{ github.repository_owner }}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          echo "$(date)" > last_update.txt  # force a file change

          git add -A .
          git commit -m "chore: updated profile contrib status" || echo "Nothing to commit"
          git push
